# Copyright 2021 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

server:
  port: 8080
  debug: true
  read_timeout_seconds: 360
  write_timeout_seconds: 360
  cors: ["*"]

database:
  request_timeout_sec: 5
  database: crawler
  collection: peers
  history_collection: history

resolver:
  request_timeout_sec: 3